### ISSUE TITLE
Custom Save Slots Request

### ISSUE THREAD

**Issue by TeavoCryptid** [Yoyolick/Boneworks-Save-Manager#2]
I just discovered this mod as I was excited for multiple save slots, as I own the only VR headset in the house and I wanted to allow my family to play Boneworks without interfering with my own save. Unfortunately, it seems that your current program only allows for a personal_save and a sandbox_save, and I was hoping you'd take the time to implement a feature for new save slots and custom save slot names.

**Comment by VREvangelist** [comment]
100% me too! My GF has a completely different Steam account and it still doesn't work for saves being different on both of them wtf Brandonjla (creator of Boneworks) and to think we could before but then they added checkpoints for casuals and ruined it even more. Sigh.

Anyways, my GF and I can't play it. Let alone guests. I am Googling for this exact thing you want TeavoCryptid and I bet many are too. That's how I found this and it's a disappointment. I don't want sandbox mode lol. I want a game I can play. Not garry's mod. Maybe after I play the game......

**Comment by zoogies** [comment]
I actually worked on a later version of this program for a little bit that had support for as many custom profiles as you wanted, if you two would like I can finish it and upload a new version here. Just let me know, if you respond ill finish it up because it was pretty close but I lost motivation.

**Comment by TeavoCryptid** [comment]
That sounds fantastic. Yeah, if you're ever able to finish it, that'd be great. Motivation is a tricky thing.

**Comment by zoogies** [comment]
Yeah, I worked on this over 6 months ago now, ill open back up visual studio and finish it because as I remember it was basically done with just a few bugs that needed to be ironed out. If you can check this thread because ill reply when it's done and close the issue. I appreciate the support, and if you have any problems or need help im Yoyo#3217 on discord

**Comment by VREvangelist** [comment]
if you don't yourself one of us I'm sure we'll post on Reddit about it and I'm sure it'll get praised. Very useful tool, my girlfriend and I aren't even able to play right now at the same time because of it. I'm playing one playthrough before her. No guests can play no family members can play.

extra sucks cuz I'm waiting to beat it before playing Half-Life alyx so it's taking extra long. I might not have it this second but I can probably donate too!
________________________________

**Comment by zoogies** [comment]
I feel the pain, I'm actually actively working on finishing it right now and there's not much left I need to do for it. Check back to this thread because I expect it to be done in a few days and ill post updates here. I appreciate you saying you're willing to donate and spread the word about it on Reddit! In a few days when i release 1.1 ill put a donation link on the wiki, and if you really like the software you can donate then. Appreciate the support boys, ill keep you updated 👍

**Comment by zoogies** [comment]
Alright, happy to say I'm finally ready to close this. Please check back in the wiki later tonight as I am currently processing an upload for a youtube video for troubleshooting/help on the project but it's pretty straightforward. In the releases tab there's an exe for 1.1 now. I ended up making a reddit post about it to spread publicity and ill also send an announcement in the boneworks discord. This wouldnt have happened without the support from you guys, so i appreciate it 😄  https://www.reddit.com/r/BoneworksMods/comments/hkuut7/boneworks_save_manager/
